# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v001.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 593, 319))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.moveArrow_layout = QtWidgets.QVBoxLayout()
        self.moveArrow_layout.setObjectName("moveArrow_layout")
        self.moveUp_toolButton = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.moveUp_toolButton.sizePolicy().hasHeightForWidth())
        self.moveUp_toolButton.setSizePolicy(sizePolicy)
        self.moveUp_toolButton.setArrowType(QtCore.Qt.UpArrow)
        self.moveUp_toolButton.setObjectName("moveUp_toolButton")
        self.moveArrow_layout.addWidget(self.moveUp_toolButton)
        self.moveDown_toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.moveDown_toolButton.setArrowType(QtCore.Qt.DownArrow)
        self.moveDown_toolButton.setObjectName("moveDown_toolButton")
        self.moveArrow_layout.addWidget(self.moveDown_toolButton)
        self.main_layout.addLayout(self.moveArrow_layout)
        self.attributes_layout = QtWidgets.QVBoxLayout()
        self.attributes_layout.setObjectName("attributes_layout")
        self.attributeAll_layoutH = QtWidgets.QHBoxLayout()
        self.attributeAll_layoutH.setObjectName("attributeAll_layoutH")
        self.attributeAll_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.attributeAll_radioButton.setText("")
        self.attributeAll_radioButton.setObjectName("attributeAll_radioButton")
        self.attributeAll_layoutH.addWidget(self.attributeAll_radioButton)
        self.attributeAll_line = QtWidgets.QFrame(self.layoutWidget)
        self.attributeAll_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.attributeAll_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attributeAll_line.setObjectName("attributeAll_line")
        self.attributeAll_layoutH.addWidget(self.attributeAll_line)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attributeAll_layoutV = QtWidgets.QVBoxLayout()
        self.attributeAll_layoutV.setObjectName("attributeAll_layoutV")
        self.attribute_layout = QtWidgets.QHBoxLayout()
        self.attribute_layout.setObjectName("attribute_layout")
        self.attributeHide_toolButton = QtWidgets.QToolButton(self.frame)
        self.attributeHide_toolButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributeHide_toolButton.sizePolicy().hasHeightForWidth())
        self.attributeHide_toolButton.setSizePolicy(sizePolicy)
        self.attributeHide_toolButton.setMouseTracking(False)
        self.attributeHide_toolButton.setIconSize(QtCore.QSize(20, 20))
        self.attributeHide_toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.attributeHide_toolButton.setAutoRaise(False)
        self.attributeHide_toolButton.setArrowType(QtCore.Qt.RightArrow)
        self.attributeHide_toolButton.setObjectName("attributeHide_toolButton")
        self.attribute_layout.addWidget(self.attributeHide_toolButton)
        self.attribute_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.attribute_lineEdit.setObjectName("attribute_lineEdit")
        self.attribute_layout.addWidget(self.attribute_lineEdit)
        self.attributeAll_layoutV.addLayout(self.attribute_layout)
        self.attributeEdits_layout = QtWidgets.QVBoxLayout()
        self.attributeEdits_layout.setObjectName("attributeEdits_layout")
        self.attributeNiceName_layout = QtWidgets.QHBoxLayout()
        self.attributeNiceName_layout.setObjectName("attributeNiceName_layout")
        self.attributeNiceName_checkBox = QtWidgets.QCheckBox(self.frame)
        self.attributeNiceName_checkBox.setObjectName("attributeNiceName_checkBox")
        self.attributeNiceName_layout.addWidget(self.attributeNiceName_checkBox)
        self.attributeNiceName_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.attributeNiceName_lineEdit.setObjectName("attributeNiceName_lineEdit")
        self.attributeNiceName_layout.addWidget(self.attributeNiceName_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeNiceName_layout)
        self.attributeMinMax_layout = QtWidgets.QHBoxLayout()
        self.attributeMinMax_layout.setObjectName("attributeMinMax_layout")
        self.attributeMin_checkBox = QtWidgets.QCheckBox(self.frame)
        self.attributeMin_checkBox.setObjectName("attributeMin_checkBox")
        self.attributeMinMax_layout.addWidget(self.attributeMin_checkBox)
        self.attributeMin_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.attributeMin_lineEdit.setObjectName("attributeMin_lineEdit")
        self.attributeMinMax_layout.addWidget(self.attributeMin_lineEdit)
        self.attributeMinMaxSep_line = QtWidgets.QFrame(self.frame)
        self.attributeMinMaxSep_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.attributeMinMaxSep_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attributeMinMaxSep_line.setObjectName("attributeMinMaxSep_line")
        self.attributeMinMax_layout.addWidget(self.attributeMinMaxSep_line)
        self.attributeMax_checkBox = QtWidgets.QCheckBox(self.frame)
        self.attributeMax_checkBox.setText("Max")
        self.attributeMax_checkBox.setObjectName("attributeMax_checkBox")
        self.attributeMinMax_layout.addWidget(self.attributeMax_checkBox)
        self.attributeMax_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.attributeMax_lineEdit.setObjectName("attributeMax_lineEdit")
        self.attributeMinMax_layout.addWidget(self.attributeMax_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeMinMax_layout)
        self.attributeStatus_layout = QtWidgets.QHBoxLayout()
        self.attributeStatus_layout.setObjectName("attributeStatus_layout")
        self.attributeKeyable_radioButton = QtWidgets.QRadioButton(self.frame)
        self.attributeKeyable_radioButton.setObjectName("attributeKeyable_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeKeyable_radioButton)
        self.attributeDisplayable_radioButton = QtWidgets.QRadioButton(self.frame)
        self.attributeDisplayable_radioButton.setObjectName("attributeDisplayable_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeDisplayable_radioButton)
        self.attributeHidden_radioButton = QtWidgets.QRadioButton(self.frame)
        self.attributeHidden_radioButton.setObjectName("attributeHidden_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeHidden_radioButton)
        self.attributeLocked_checkBox = QtWidgets.QCheckBox(self.frame)
        self.attributeLocked_checkBox.setObjectName("attributeLocked_checkBox")
        self.attributeStatus_layout.addWidget(self.attributeLocked_checkBox)
        self.attributeEdits_layout.addLayout(self.attributeStatus_layout)
        self.attributeDValue_layout = QtWidgets.QHBoxLayout()
        self.attributeDValue_layout.setObjectName("attributeDValue_layout")
        self.attributeDValue_label = QtWidgets.QLabel(self.frame)
        self.attributeDValue_label.setObjectName("attributeDValue_label")
        self.attributeDValue_layout.addWidget(self.attributeDValue_label)
        self.attributeDValue_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.attributeDValue_lineEdit.setObjectName("attributeDValue_lineEdit")
        self.attributeDValue_layout.addWidget(self.attributeDValue_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeDValue_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()

        ################################################################################################################

        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.attributeEdits_layout.addLayout(self.horizontalLayout)
        self.attributeAll_layoutV.addLayout(self.attributeEdits_layout)
        self.verticalLayout.addLayout(self.attributeAll_layoutV)
        self.attributeAll_layoutH.addWidget(self.frame)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.attributeAll_layoutH.addWidget(self.pushButton)
        self.attributes_layout.addLayout(self.attributeAll_layoutH)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_5.addWidget(self.radioButton_5)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_7.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_7.setAutoRaise(False)
        self.toolButton_7.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_6.addWidget(self.toolButton_7)
        self.val1_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.val1_2.setObjectName("val1_2")
        self.horizontalLayout_6.addWidget(self.val1_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.attributes_layout.addLayout(self.horizontalLayout_5)
        self.main_layout.addLayout(self.attributes_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.moveUp_toolButton, self.moveDown_toolButton)
        MainWindow.setTabOrder(self.moveDown_toolButton, self.attributeNiceName_checkBox)
        MainWindow.setTabOrder(self.attributeNiceName_checkBox, self.attributeNiceName_lineEdit)
        MainWindow.setTabOrder(self.attributeNiceName_lineEdit, self.attributeKeyable_radioButton)
        MainWindow.setTabOrder(self.attributeKeyable_radioButton, self.attributeDisplayable_radioButton)
        MainWindow.setTabOrder(self.attributeDisplayable_radioButton, self.attributeHidden_radioButton)
        MainWindow.setTabOrder(self.attributeHidden_radioButton, self.attributeLocked_checkBox)
        MainWindow.setTabOrder(self.attributeLocked_checkBox, self.attributeMin_checkBox)
        MainWindow.setTabOrder(self.attributeMin_checkBox, self.attributeMin_lineEdit)
        MainWindow.setTabOrder(self.attributeMin_lineEdit, self.attributeMax_checkBox)
        MainWindow.setTabOrder(self.attributeMax_checkBox, self.attributeMax_lineEdit)
        MainWindow.setTabOrder(self.attributeMax_lineEdit, self.attributeDValue_lineEdit)
        MainWindow.setTabOrder(self.attributeDValue_lineEdit, self.toolButton_7)
        MainWindow.setTabOrder(self.toolButton_7, self.val1_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moveUp_toolButton.setText(_translate("MainWindow", "..."))
        self.moveDown_toolButton.setText(_translate("MainWindow", "..."))
        self.attributeHide_toolButton.setText(_translate("MainWindow", "..."))
        self.attributeNiceName_checkBox.setText(_translate("MainWindow", "Nice Name"))
        self.attributeMin_checkBox.setText(_translate("MainWindow", "Min"))
        self.attributeKeyable_radioButton.setText(_translate("MainWindow", "Keyable"))
        self.attributeDisplayable_radioButton.setText(_translate("MainWindow", "Displayable"))
        self.attributeHidden_radioButton.setText(_translate("MainWindow", "Hidden"))
        self.attributeLocked_checkBox.setText(_translate("MainWindow", "Locked"))
        self.attributeDValue_label.setText(_translate("MainWindow", "Default"))
        self.label.setText(_translate("MainWindow", "Enum names"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "bla"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "bli"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "blo"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.val1_2.setText(_translate("MainWindow", "Val2"))

