# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_v001.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.moveArrow_layout = QtWidgets.QVBoxLayout()
        self.moveArrow_layout.setObjectName("moveArrow_layout")
        self.moveUp_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.moveUp_toolButton.setArrowType(QtCore.Qt.UpArrow)
        self.moveUp_toolButton.setObjectName("moveUp_toolButton")
        self.moveArrow_layout.addWidget(self.moveUp_toolButton)
        self.moveDown_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.moveDown_toolButton.setArrowType(QtCore.Qt.DownArrow)
        self.moveDown_toolButton.setObjectName("moveDown_toolButton")
        self.moveArrow_layout.addWidget(self.moveDown_toolButton)
        self.main_layout.addLayout(self.moveArrow_layout)
        self.main_line = QtWidgets.QFrame(self.centralwidget)
        self.main_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.main_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.main_line.setObjectName("main_line")
        self.main_layout.addWidget(self.main_line)
        self.attributes_layout = QtWidgets.QVBoxLayout()
        self.attributes_layout.setObjectName("attributes_layout")
        self.attributeAll_layoutH = QtWidgets.QHBoxLayout()
        self.attributeAll_layoutH.setObjectName("attributeAll_layoutH")
        self.attributeAll_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.attributeAll_radioButton.setText("")
        self.attributeAll_radioButton.setObjectName("attributeAll_radioButton")
        self.attributeAll_layoutH.addWidget(self.attributeAll_radioButton)
        self.attributeAll_line = QtWidgets.QFrame(self.centralwidget)
        self.attributeAll_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.attributeAll_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attributeAll_line.setObjectName("attributeAll_line")
        self.attributeAll_layoutH.addWidget(self.attributeAll_line)
        self.attributeAll_layoutV = QtWidgets.QVBoxLayout()
        self.attributeAll_layoutV.setObjectName("attributeAll_layoutV")
        self.attribute_layout = QtWidgets.QHBoxLayout()
        self.attribute_layout.setObjectName("attribute_layout")
        self.attributeHide_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.attributeHide_toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.attributeHide_toolButton.setAutoRaise(False)
        self.attributeHide_toolButton.setArrowType(QtCore.Qt.RightArrow)
        self.attributeHide_toolButton.setObjectName("attributeHide_toolButton")
        self.attribute_layout.addWidget(self.attributeHide_toolButton)
        self.attribute_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.attribute_lineEdit.setObjectName("attribute_lineEdit")
        self.attribute_layout.addWidget(self.attribute_lineEdit)
        self.attributeAll_layoutV.addLayout(self.attribute_layout)
        self.attributeEdits_layout = QtWidgets.QVBoxLayout()
        self.attributeEdits_layout.setObjectName("attributeEdits_layout")
        self.attributeNiceName_layout = QtWidgets.QHBoxLayout()
        self.attributeNiceName_layout.setObjectName("attributeNiceName_layout")
        self.attributeNiceName_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.attributeNiceName_checkBox.setObjectName("attributeNiceName_checkBox")
        self.attributeNiceName_layout.addWidget(self.attributeNiceName_checkBox)
        self.attributeNiceName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.attributeNiceName_lineEdit.setObjectName("attributeNiceName_lineEdit")
        self.attributeNiceName_layout.addWidget(self.attributeNiceName_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeNiceName_layout)
        self.attributeStatus_layout = QtWidgets.QHBoxLayout()
        self.attributeStatus_layout.setObjectName("attributeStatus_layout")
        self.attributeKeyable_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.attributeKeyable_radioButton.setObjectName("attributeKeyable_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeKeyable_radioButton)
        self.attributeDisplayable_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.attributeDisplayable_radioButton.setObjectName("attributeDisplayable_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeDisplayable_radioButton)
        self.attributeHidden_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.attributeHidden_radioButton.setObjectName("attributeHidden_radioButton")
        self.attributeStatus_layout.addWidget(self.attributeHidden_radioButton)
        self.attributeLocked_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.attributeLocked_checkBox.setObjectName("attributeLocked_checkBox")
        self.attributeStatus_layout.addWidget(self.attributeLocked_checkBox)
        self.attributeEdits_layout.addLayout(self.attributeStatus_layout)
        self.attributeMinMax_layout = QtWidgets.QHBoxLayout()
        self.attributeMinMax_layout.setObjectName("attributeMinMax_layout")
        self.attributeMin_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.attributeMin_checkBox.setObjectName("attributeMin_checkBox")
        self.attributeMinMax_layout.addWidget(self.attributeMin_checkBox)
        self.attributeMin_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.attributeMin_lineEdit.setObjectName("attributeMin_lineEdit")
        self.attributeMinMax_layout.addWidget(self.attributeMin_lineEdit)
        self.attributeMinMaxSep_line = QtWidgets.QFrame(self.centralwidget)
        self.attributeMinMaxSep_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.attributeMinMaxSep_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attributeMinMaxSep_line.setObjectName("attributeMinMaxSep_line")
        self.attributeMinMax_layout.addWidget(self.attributeMinMaxSep_line)
        self.attributeMax_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.attributeMax_checkBox.setObjectName("attributeMax_checkBox")
        self.attributeMinMax_layout.addWidget(self.attributeMax_checkBox)
        self.attributeMax_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.attributeMax_lineEdit.setObjectName("attributeMax_lineEdit")
        self.attributeMinMax_layout.addWidget(self.attributeMax_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeMinMax_layout)
        self.attributeDValue_layout = QtWidgets.QHBoxLayout()
        self.attributeDValue_layout.setObjectName("attributeDValue_layout")
        self.attributeDValue_label = QtWidgets.QLabel(self.centralwidget)
        self.attributeDValue_label.setObjectName("attributeDValue_label")
        self.attributeDValue_layout.addWidget(self.attributeDValue_label)
        self.attributeDValue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.attributeDValue_lineEdit.setObjectName("attributeDValue_lineEdit")
        self.attributeDValue_layout.addWidget(self.attributeDValue_lineEdit)
        self.attributeEdits_layout.addLayout(self.attributeDValue_layout)
        self.attributeAll_layoutV.addLayout(self.attributeEdits_layout)
        self.attributeAll_layoutH.addLayout(self.attributeAll_layoutV)
        self.attributes_layout.addLayout(self.attributeAll_layoutH)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_5.addWidget(self.radioButton_5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_7.setAutoRaise(False)
        self.toolButton_7.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_6.addWidget(self.toolButton_7)
        self.val1_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.val1_2.setObjectName("val1_2")
        self.horizontalLayout_6.addWidget(self.val1_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.attributes_layout.addLayout(self.horizontalLayout_5)
        self.main_layout.addLayout(self.attributes_layout)
        self.verticalLayout.addLayout(self.main_layout)
        self.attributeKeyable_radioButton.raise_()
        self.attributeDisplayable_radioButton.raise_()
        self.attributeHidden_radioButton.raise_()
        self.attributeHide_toolButton.raise_()
        self.attributeNiceName_lineEdit.raise_()
        self.attributeNiceName_checkBox.raise_()
        self.attributeMin_checkBox.raise_()
        self.attributeMin_lineEdit.raise_()
        self.attributeMax_checkBox.raise_()
        self.attributeMax_lineEdit.raise_()
        self.attributeMinMaxSep_line.raise_()
        self.attributeDValue_label.raise_()
        self.attributeDValue_lineEdit.raise_()
        self.attributeLocked_checkBox.raise_()
        self.val1_2.raise_()
        self.toolButton_7.raise_()
        self.val1_2.raise_()
        self.attributeHide_toolButton.raise_()
        self.toolButton_7.raise_()
        self.attributeMax_lineEdit.raise_()
        self.attributeKeyable_radioButton.raise_()
        self.attributeDValue_label.raise_()
        self.attributeNiceName_lineEdit.raise_()
        self.attributeHidden_radioButton.raise_()
        self.attributeMax_checkBox.raise_()
        self.attributeDisplayable_radioButton.raise_()
        self.attributeMinMaxSep_line.raise_()
        self.attributeMin_checkBox.raise_()
        self.moveDown_toolButton.raise_()
        self.attributeMin_lineEdit.raise_()
        self.moveUp_toolButton.raise_()
        self.attributeNiceName_checkBox.raise_()
        self.attributeDValue_lineEdit.raise_()
        self.attributeLocked_checkBox.raise_()
        self.val1_2.raise_()
        self.attributeHide_toolButton.raise_()
        self.toolButton_7.raise_()
        self.attributeMax_lineEdit.raise_()
        self.attributeKeyable_radioButton.raise_()
        self.attributeDValue_label.raise_()
        self.attributeNiceName_lineEdit.raise_()
        self.attributeHidden_radioButton.raise_()
        self.attributeMax_checkBox.raise_()
        self.attributeDisplayable_radioButton.raise_()
        self.attributeMinMaxSep_line.raise_()
        self.attributeMin_checkBox.raise_()
        self.moveDown_toolButton.raise_()
        self.attributeMin_lineEdit.raise_()
        self.moveUp_toolButton.raise_()
        self.attributeNiceName_checkBox.raise_()
        self.attributeDValue_lineEdit.raise_()
        self.attributeLocked_checkBox.raise_()
        self.attributeAll_radioButton.raise_()
        self.attributeAll_radioButton.raise_()
        self.radioButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.moveUp_toolButton, self.moveDown_toolButton)
        MainWindow.setTabOrder(self.moveDown_toolButton, self.attributeNiceName_checkBox)
        MainWindow.setTabOrder(self.attributeNiceName_checkBox, self.attributeNiceName_lineEdit)
        MainWindow.setTabOrder(self.attributeNiceName_lineEdit, self.attributeKeyable_radioButton)
        MainWindow.setTabOrder(self.attributeKeyable_radioButton, self.attributeDisplayable_radioButton)
        MainWindow.setTabOrder(self.attributeDisplayable_radioButton, self.attributeHidden_radioButton)
        MainWindow.setTabOrder(self.attributeHidden_radioButton, self.attributeLocked_checkBox)
        MainWindow.setTabOrder(self.attributeLocked_checkBox, self.attributeMin_checkBox)
        MainWindow.setTabOrder(self.attributeMin_checkBox, self.attributeMin_lineEdit)
        MainWindow.setTabOrder(self.attributeMin_lineEdit, self.attributeMax_checkBox)
        MainWindow.setTabOrder(self.attributeMax_checkBox, self.attributeMax_lineEdit)
        MainWindow.setTabOrder(self.attributeMax_lineEdit, self.attributeDValue_lineEdit)
        MainWindow.setTabOrder(self.attributeDValue_lineEdit, self.toolButton_7)
        MainWindow.setTabOrder(self.toolButton_7, self.val1_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moveUp_toolButton.setText(_translate("MainWindow", "..."))
        self.moveDown_toolButton.setText(_translate("MainWindow", "..."))
        self.attributeHide_toolButton.setText(_translate("MainWindow", "..."))
        self.attributeNiceName_checkBox.setText(_translate("MainWindow", "Nice Name"))
        self.attributeKeyable_radioButton.setText(_translate("MainWindow", "Keyable"))
        self.attributeDisplayable_radioButton.setText(_translate("MainWindow", "Displayable"))
        self.attributeHidden_radioButton.setText(_translate("MainWindow", "Hidden"))
        self.attributeLocked_checkBox.setText(_translate("MainWindow", "Locked"))
        self.attributeMin_checkBox.setText(_translate("MainWindow", "Min"))
        self.attributeMax_checkBox.setText(_translate("MainWindow", "Max"))
        self.attributeDValue_label.setText(_translate("MainWindow", "Default"))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.val1_2.setText(_translate("MainWindow", "Val2"))

